/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_agent_CmdAgent */

#ifndef _Included_com_company_agent_CmdAgent
#define _Included_com_company_agent_CmdAgent
#ifdef __cplusplus
extern "C" {
#endif
#undef com_company_agent_CmdAgent_beaconInterval
#define com_company_agent_CmdAgent_beaconInterval 5L
/*
 * Class:     com_company_agent_CmdAgent
 * Method:    C_GetLocalTime
 * Signature: (Lcom/company/shared/cmds/GetLocalTime;)Lcom/company/shared/cmds/GetLocalTime;
 */
JNIEXPORT jobject JNICALL Java_com_company_agent_CmdAgent_C_1GetLocalTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_company_agent_CmdAgent
 * Method:    C_GetLocalOs
 * Signature: (Lcom/company/shared/cmds/GetLocalOs;)Lcom/company/shared/cmds/GetLocalOs;
 */
JNIEXPORT jobject JNICALL Java_com_company_agent_CmdAgent_C_1GetLocalOs
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
